
volumes:
  postgres-data:
  outline-data:

services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:0.82.0
    restart: unless-stopped
    ports:
      - ${OUTLINE_PORT}:8080
    volumes:
      - outline-data:/var/lib/outline/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGSSLMODE=disable
      - FILE_STORAGE=local
      - FORCE_HTTPS=false
      - SECRET_KEY=${SECRET_KEY}
      - UTILS_SECRET=${UTILS_SECRET}
      - DATABASE_URL=postgres://${SQL_USER}:${SQL_PASSWORD}@${SQL_HOST}:5432/${SQL_DBNAME}
      - REDIS_URL=redis://${REDIS_HOST}:6379
      - URL=${WIKI_URL}
      - PORT=8080
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_SERVER_ID=${DISCORD_SERVER_ID}
      - DISCORD_SERVER_ROLES=${DISCORD_SERVER_ROLES}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_RESOURCE_APP_ID=${AZURE_RESOURCE_APP_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - FILE_STORAGE_UPLOAD_MAX_SIZE=${FILE_STORAGE_UPLOAD_MAX_SIZE}
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:5.0.3-alpine
    restart: unless-stopped

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=${SQL_USER} --dbname=${SQL_DBNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_DB=${SQL_DBNAME}
